language: node_js
node_js:
  - "0.10"
#  - "0.11"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
  
  
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
  
install:
  - sudo apt-get install graphicsmagick
  
script: "npm run-script test-travis"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
